name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #dependency-injection:
  get: ^4.6.6
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  http: ^1.2.1
  #localization
  intl: ^0.20.1
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.2.4
  logger: ^2.3.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/on_boarding_images/
    - assets/images/verify_email_images/
    - assets/logos/
    - assets/images/carousel_images/
    - assets/images/shoes/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
   
  